version: "3.9"

networks:
  contact:
    driver: bridge

services:
  backend:
    image: acavinash/contact-backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node dist/server.js"
    env_file:
      - .env
    networks:
      - contact

  frontend:
    image: acavinash/contact-frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - contact





